### ISSUE TITLE
ignore ENOTSUPP (524) for fiemap error

### ISSUE THREAD

**Issue by defaziogiancarlo** [hpc/mpifileutils#644]
In mfu_flist_copy.c:mfu_copy_file_fiemap()

```C
    if (ioctl(mfu_src_file->fd, FS_IOC_FIEMAP, fiemap) < 0) {
        if (errno == ENOTSUP) {
            /* silently ignore */
        } else {
            MFU_LOG(MFU_LOG_ERR, "fiemap ioctl() failed for src '%s' (errno=%d %s)",
                    src, errno, strerror(errno));
        }
        goto fail_fiemap;
    }
```

When errno is ENOTSUP (95) the error message is skipped, but otherwise the behavior is the same. However lustre often returns ENOTSUPP (524) as mentioned in #545. I think that (errno == 524) should be silently ignored as well.

**Comment by adilger** [comment]
Hmm, this should have been fixed in Lustre commit v2_13_57-49-g71a9f5a466 ("LU-14301 llite: return EOPNOTSUPP if fallocate is not supported") so it should be included in 2.15.7.

On a related note - SEEK_HOLE and SEEK_DATA are preferred over FIEMAP for copying data. Their interpretation is much less complex than FIEMAP.

**Comment by defaziogiancarlo** [comment]
It looks like I miss read the comments of #545 and read EOPNOTSUPP as ENOTSUPP. So I thought it was expected that lustre would return ENOTSUPP in this case and didn't investigate if there was a lustre patch for this. As mentioned above there's a patch to fix this, although I think it's (LU-14301 client: use EOPNOTSUPP instead of ENOTSUPP) which isn't in lustre 2.15. The other patches from LU-14301 are.

**Comment by ofaaland** [comment]
I tested on mutt with a lustre-2.15.7_1.llnl-1.t4.x86_64 client and still get 524 instead of 95.

**Comment by defaziogiancarlo** [comment]
verified that error message with 524 goes away when (LU-14301 client: use EOPNOTSUPP instead of ENOTSUPP) https://review.whamcloud.com/51511 is applied to 2.15.7_1.llnl
